version: "3.8"
services:
  synthetic-monitoring:
    build: .
    container_name: synthetic-monitoring-c
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - CRON_SCHEDULE=*/1 * * * *
      - MONGO_URI=<> # MongoDB URI
